dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: m9zPhJ+hd3Ngw9gBQtrbhlo9TXHRBYTr0nxp2yBbpo8CCXNPpxoN81RSpNsK/6Y+D/yhUHMvIt+2Ny8L93R4YVA2P+CrNXasJVQuJMJ9ChSc+V3vBhckc1wRXjaTNUo2QJSefhM0h+aLwaKvBtNnuo4AUkyhmk4BsgKINIBw+R0x6Jtb22NEWzSi0Zv3G8ttQ1HFb4M68BZ9F7wpukGOkoqK6jg1vvW4E+RRnnHiO8bQKj2kLCwYxuMpMYTDAJVA9ffGwSPBEvyWg19R493jQNvL8q8oM70AaEYy/g1bi25kZ8ZJpw9wtHdLnUdlTSbUSqKdOJpOCS/sMgDB96irvRwOjYwUB8jQZZ2uftrm3o2vSlzUCkfuFxlOxO5/DYxjdx6eEgJY3xv/BjrfA2C+GJ2R9PzZLobRiCci6TzB44rGpVaGrHdZJpQsybJGqSR3jts+XuPTgxkFAQxIgnikDyr7MIyumb7VnVQNYa5LEYx7muTP7ncmS/b743UhFxLQKqSgsojEPyU0Ph22uThFOjxtgC9ihMnfH2QuMsBSM1RKI7TxqsI4KWOO7jJ+pHOmzGNtKYj99VamRGq5RyxQz8Cjv7fTtlkG4i2c6KvEqG7Wbhfv0qXMqQk+o4gSmCF3HZFJb9EpfU+zIO1weqtqCRXl4w2c7+0PzeYmZJHF47I=
